SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME
FROM ANIMAL_INS AS I
LEFT JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE <> O.SEX_UPON_OUTCOME
AND SUBSTRING(I.SEX_UPON_INTAKE, 1, 6) = 'Intact';