WITH RECURSIVE GENERATION_CTE AS (
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT 
        e.ID,
        e.PARENT_ID,
        g.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN GENERATION_CTE g
      ON e.PARENT_ID = g.ID
),

LEAF_CHECK AS (
    SELECT 
        g.ID,
        g.GENERATION,
        c.ID AS CHILD_ID
    FROM GENERATION_CTE g
    LEFT JOIN ECOLI_DATA c
      ON g.ID = c.PARENT_ID
)

SELECT 
    COUNT(*) AS COUNT,
    GENERATION
FROM LEAF_CHECK
WHERE CHILD_ID IS NULL  
GROUP BY GENERATION
ORDER BY GENERATION;
