SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS r
JOIN MEMBER_PROFILE AS p ON r.MEMBER_ID = p.MEMBER_ID
WHERE r.MEMBER_ID = (
    SELECT r1.MEMBER_ID
    FROM REST_REVIEW AS r1
    GROUP BY r1.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;
