SELECT 
    C.ITEM_ID,
    C.ITEM_NAME,
    C.RARITY
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS P
    ON T.PARENT_ITEM_ID = P.ITEM_ID   
JOIN ITEM_INFO AS C
    ON T.ITEM_ID = C.ITEM_ID        
WHERE P.RARITY = 'RARE'             
ORDER BY C.ITEM_ID DESC;