SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO AS i
JOIN FISH_NAME_INFO AS n ON i.FISH_TYPE = n.FISH_TYPE
JOIN (
    SELECT n.FISH_TYPE, MAX(i.LENGTH) AS MAX_LENGTH
    FROM FISH_INFO AS i
    JOIN FISH_NAME_INFO AS n ON i.FISH_TYPE = n.FISH_TYPE
    GROUP BY n.FISH_TYPE
) AS max_fish ON i.FISH_TYPE = max_fish.FISH_TYPE AND i.LENGTH = max_fish.MAX_LENGTH
ORDER BY i.ID ASC;
